 /******************************************************
 * PLEASE DO NOT EDIT THIS FILE !!!
 * The Verification Process Might Break
 * ***************************************************/

'use strict';


// Respond not found to all the wrong routes


// Middleware Errors?


app.listen(process.env.PORT, function () {
    console.log('Node.js listening ...');
});
